DROP TABLE IF EXISTS organizers CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS timeslots CASCADE;
DROP TABLE IF EXISTS attendees CASCADE;
DROP TABLE IF EXISTS guest_lists CASCADE;

CREATE TABLE organizers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL
  );

CREATE TABLE events (
  id SERIAL PRIMARY KEY NOT NULL,
  url TEXT NOT NULL,
  name VARCHAR(255) NOT NULL,
  -- should description be mandatory?
  description TEXT,
  location VARCHAR(50) NOT NULL,
  organizer_id INTEGER NOT NULL REFERENCES organizers(id) ON DELETE CASCADE
  );

CREATE TABLE timeslots (
  id SERIAL PRIMARY KEY NOT NULL,
  start_time
  end_time
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE
  );

CREATE TABLE attendees (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL
  );

CREATE TABLE guest_lists (
  attendee_id INTEGER NOT NULL REFERENCES attendees(id) ON DELETE CASCADE,
  timeslot_id INTEGER NOT NULL REFERENCES timeslots(id) ON DELETE CASCADE
  );
